### ISSUE TITLE
Speedtest Accept license

### ISSUE THREAD

**Issue by burneystarke** [tianon/dockerfiles#111]
Running
docker run --rm --net=host tianon/speedtest
Gives

...
To accept the message please run speedtest interactively or use the follow:
     speedtest --accept-license
...

The recommended command should be
docker run --rm --net=host tianon/speedtest --accept-license

**Comment by tianon** [comment]
I thought about this, but I don't want to suggest that users should blindly accept the Speedtest license. :confused:

(Especially since the upstream authors went to the trouble of forcing this to be explicitly specified.)

If you run it interactively instead, it will prompt, and save your answer in a file (which could be stored in a volume).

**Comment by LoveIsGrief** [comment]
I do agree with @tianon : users shouldn't unknowingly be accepting EULAs they might not agree with. Maybe simply adding it to the README would be enough? 

P.S thank for the image! Very useful for collecting stats :slightly_smiling_face:

**Comment by burneystarke** [comment]
Agreed, I'll close this. As @LoveIsGrief mentioned, maybe it can make its way into the README if it hasn't already!
