### ISSUE TITLE
Question: where to see Dockerfile for tianon/centos:6.5

### ISSUE THREAD

**Issue by cch0** [tianon/dockerfiles#142]
I am looking for the `Dockerfile` which built `tianon/centos:6.5`.  

The reason is to find out whether or not it is based on `debian:buster-slim`. I am interested in building `tianon/centos:6.5` again which supports ARM architecture in addition to AMD.

**Comment by tianon** [comment]
It was not based on `debian` (it's a raw build of CentOS 6).  It was built using [the `rinse` tool](https://salsa.debian.org/debian/rinse) via the https://github.com/moby/moby/blob/72c21a7e5d8da44b39fc95b84efc2dbc5038f938/contrib/mkimage/rinse script (which has since been removed, since it was unmaintained).
