### ISSUE TITLE
speedtest accept license

### ISSUE THREAD

**Issue by nopoz** [tianon/dockerfiles#189]
If you run the default command listed in the speedtest README.md:

```
docker run --rm --net=host tianon/speedtest
```

The speedtest executable spits out the following lines and quits:

```
To accept the message please run speedtest interactively or use the following:

    speedtest --accept-license
```

In order to get the test to run with the current container config you need to modify the command to be:

```
docker run --rm --net=host tianon/speedtest speedtest --accept-license
```

My suggestion would be to alter the docker container cmd to include `--accept-license` or alter the README.md to include this extra parameter. Thanks!

**Comment by tianon** [comment]
Oops, good catch!  This is a disparity caused by Ookla's `speedtest` vs the old `speedtest-cli` I used to publish under this same name.

I do _not_ feel comfortable adding (or even suggesting) `--accept-license` unilaterally, since there is a license for a reason, so I think my preferred solution here would be to add `-it` to the example command (and leave more complex usage like pre-accepting the license or saving a volume for the license acceptance marker file as an exercise for the user).

**Comment by tianon** [comment]
... and now also updated on Docker Hub -- thank you! :+1:
