### ISSUE TITLE
ehour doesn't seem to be running

### ISSUE THREAD

**Issue by ZenergyBryson** [tianon/dockerfiles#359]
I have configured the ehour.properties file and have it pushed into the container.  Using docker exec I can see the ehour.log
```/usr/local/ehour# cat home/log/ehour.log 
12-09@21:11:49 INFO  org.eclipse.jetty.server.Server - jetty-8.1.16.v20140903
12-09@21:11:49 WARN  org.eclipse.jetty.server.handler.RequestLogHandler - !RequestLog
12-09@21:11:49 INFO  org.eclipse.jetty.deploy.providers.ScanningAppProvider - Deployment monitor /usr/local/ehour/home/conf/contexts at interval 5
12-09@21:11:49 INFO  org.eclipse.jetty.deploy.DeploymentManager - Deployable added: /usr/local/ehour/home/conf/contexts/ehourweb.xml
12-09@21:11:49 INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
12-09@21:11:49 INFO  net.rrm.ehour.ui.listener.EnvInitListener - EHOUR_HOME set to /usr/local/ehour/home
12-09@21:11:49 INFO  / - Initializing Spring root WebApplicationContext
12-09@21:11:49 INFO  org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
```
Is there anything in there that tells you it's working or not?  That's all the log says, ever.
From the host, I can `curl localhost:8000` and I get a 503 error "Service Unavailable"  -- likewise when I visit the site in a browser (nginx is pointed to 8000)
Thoughts?  I'm stumped.

**Comment by tianon** [comment]
I removed `ehour` from my supported set in 71f5e918f08bc4fe7ef30f4c1002b6d682ed3e2e because I no longer use it (and the build was failing); also https://ehour.nl/ makes it pretty clear that it's no longer maintained, so I'd really not recommend it. :sweat_smile:

(I was only using it for so long because switching systems is hard once you're even slightly entrenched. :weary:)

Usually when I'd get 503s from it, it was because my database had a hiccup or something and restarting my eHour container would usually resolve it, but unfortunately I'm not going to be much help beyond that. :see_no_evil:

**Comment by ZenergyBryson** [comment]
Thanks for the quick reply.  I don't have much choice in the selection, unfortunately - it's just what we use at work and I'm trying to help them get it moved from a physical (old Dell workstation) server to AWS.
I'll investigate the database thing - I'd bet you're correct, since I'm pointed at RDS.

**Comment by tianon** [comment]
I'm going to go ahead and close this, but feel free to continue posting here if you feel like there's more that's useful to add. :sweat_smile:
