### ISSUE TITLE
More explanation about how to get exim4 working with a php container ?

### ISSUE THREAD

**Issue by ouraios** [tianon/dockerfiles#43]
Hello, 
I was wondering if it could be possible to add more explanation with a given example of how to get the exim4 container working with a php container ?
Because from your README i dont really see how to configure my php container to tell him to use exim4 to send mails :/

(I'm pretty new to the docker world and i'm using a docker-compose.yml to get all my containers working)

**Comment by tianon** [comment]
I usually install `ssmtp` (which then provides `sendmail`), and configure it something like this:
```dockerfile
RUN { \
	echo 'Mailhub=exim4'; \
	echo 'FromLineOverride=yes'; \
} > /etc/ssmtp/ssmtp.conf
```

**Comment by ouraios** [comment]
And what if i dont want to install ssmtp ?? how can i do without it ?

**Comment by tianon** [comment]
Connect via SMTP directly to the running exim4 instance.

**Comment by ouraios** [comment]
Okay i see, two more questions :

 - `-v /etc/mailname:/etc/mailname:ro -h "$(cat /etc/mailname)` : how the content of the `mailname` file should be ?
```
myhost.com
second.myhost.com
```
Or something else ?

- if exim configtype is set on `internet ` how can i configure exim to use my dkim key ? 

Sry in advance if my questions look a bit dumb :/

**Comment by ouraios** [comment]
Apparently exim is always sending mail to example.com, how can i change that ?

**Comment by tianon** [comment]
To be quite honest, I don't know all that much about configuring exim4 to do more interesting things -- I usually just look up enough documentation to do the one or two things I need right now (or to debug whatever odd behavior I'm seeing), and call it good.  I'd recommend finding an exim4 users group, mailing list, or support forum if you've got further questions (because I'm definitely out of my depth -- the image does what I need it to as-is, which is send email directly or via Gmail as an SMTP target for my other containers). :innocent: :+1:

Sorry!

**Comment by ouraios** [comment]
Hmmm well, i want it to just send email directly to but it's not working apparently :/
Thanks anyway for your help so far,  i'll contact a user from exim to see with how it works :)
