### ISSUE TITLE
Set WORKDIR for docker

### ISSUE THREAD

**Issue by tmaier** [tianon/dockerfiles#48]
The default workdir is `/`. This makes it quite inconvenient to run a build with docker container run --rm

```
docker container run -v $(pwd):/workdir --rm tianon/latex:latest xelatex index.tex
```

Please set `WORKDIR` in the Dockerfile.

**Comment by tianon** [comment]
The problem is that then we get to debate what that default `WORKDIR` value should be.  Instead, I'd recommend using `-w` to set it to the explicit path you're bind-mounting to, ala:
```console
docker container run -v $PWD:/workdir -w /workdir --rm tianon/latex:latest xelatex index.tex
```

Also, you might want to include something like `-u "$(id -u):$(id -g)"` so `xelatex` runs as your current user instead of `root`, thus allowing proper permissions on the files it creates.
