### ISSUE TITLE
[latex] Pygments

### ISSUE THREAD

**Issue by rubdos** [tianon/dockerfiles#62]
I use your LaTeX image for CI (using Gitlab) on a lot of documents (esp. exercises for teaching). I use a lot of minted in these things. It's a bit sad that I have to add

```bash
apt-get update && apt-get install -y python-chardet python-pkg-resources python-pip
pip install Pygments
```
to all of my builds. Would you consider having Pygments installed in that image, or an extension of your image?

**Comment by tianon** [comment]
I mean, the current `Dockerfile` is pretty slim:

https://github.com/tianon/dockerfiles/blob/8f268166258d2826574a987130a0eafe1f34223d/latex/Dockerfile#L1-L8

You _could_ create yourself a short `Dockerfile` with an automated build to have one that builds from mine and adds `pygments` (because I don't think needing Pygments for LaTeX is a common enough requirement for me to add it to the already enormously bloated image), but at that point you really might as well simply copy my `Dockerfile` as a starting point and just ditch me. :smile:

**Comment by rubdos** [comment]
> You _could_ create yourself a short `Dockerfile` with an automated build to have one that builds from mine and adds `pygments` (because I don't think needing Pygments for LaTeX is a common enough requirement for me to add it to the already enormously bloated image), but at that point you really might as well simply copy my `Dockerfile` as a starting point and just ditch me. :smile:

I'm not ditching you! <3 :-)

I'll build something on top of it then indeed. Might as well bloat it further with stuff I use at that point. Sorry for bothering you :-)
