### ISSUE TITLE
repeatedly deleting and re-downloading Packages files?

### ISSUE THREAD

**Issue by craig-sanders** [tianon/dockerfiles#91]
I'm just wondering why your steam Dockerfile runs `apt-get update` and then runs `rm -rf /var/lib/apt/lists/*` multiple times?

Wouldn't it be better to do this at the start of the Dockerfile:

    RUN set -eux; \
	dpkg --add-architecture i386; \
	apt-get update

and clean up at the end (just before the `USER steam` and `CMD ["steam"]` lines):

    RUN set -eux; \
      rm -f steam.deb; \
      rm -rf /var/lib/apt/lists/*

That would avoid having to run `apt-get update` (and downloading all the Packages files) multiple times.

**Comment by SuperSandro2000** [comment]
No, it wouldn't because we would have cached the apt lists in a layer and would download them there. You could combine all ``apt`` into one ``RUN``.

**Comment by craig-sanders** [comment]
Whether you use a local mirror or apt-cacher or an http proxy or something else to cache them, they still have to be downloaded into the container again every time you run `apt-get update`, causing at least local network IO (or loopback IO if the cache is on the same machine as the docker build host) plus disk IO to write the Packages lists into the container's /var/lib/apt/lists/ directory again.   And there's also significant CPU time for apt-get to read & process the Package lists again.

No matter the caching, it would be faster to not have to do that multiple times.  It's much better to run `apt-get update` once, then run `apt-get install` as often as desired, and *then* delete the package lists as cleanup when finishing the build - i.e. when you definitely don't need them any more.

---

BTW, I run a local debian mirror on my own LAN. Running `apt-get update` takes anywhere from 3 to 6.5 seconds (on a threadripper 1950x with 64GB. rootfs including /var/lib/apt on an nvme ssd.  gigabit ethernet).  3 seconds if it doesn't need to download the lists again or rewrite anything in /var/lib/apt/lists.  6+ if it does.   Deleting the package lists prematurely guarantees the worst case....but if you don't delete the package lists, you don't even need to run `apt-get update` again.

First run:

```
# time apt-get update
[20 "Get:" & "Ign:" lines for "InRelease", "Packages", and "Translation-en" files]
Fetched 24.0 MB in 3s (8,188 kB/s)                               
Reading package lists... Done

real 0m6.557s	user 0m6.006s	sys 0m0.613s
```
Second run (no downloads or updates needed):

```
# time apt-get update
[2 "Hit:" lines, for "InRelease" files only]
Reading package lists... Done

real 0m3.042s	user 0m2.630s	sys 0m0.399s
```


BTW, a first run on one of my FX-8320 machines takes 10.2 seconds. And on my Phenom II 1090T (which is the machine hosting my debian mirror), it takes 18.3 seconds.  Second runs are 5.7 and 12.0 seconds respectively.

IMO, eliminating multiple unnecessary delays like these is worthwhile. In the steam Dockerfile, there's two unnecessary runs of `apt-get update`....wasting, e.g, 12 to 36 seconds per build, depending on hardware.

**Comment by tianon** [comment]
I think the *Docker* build cache is the bit you're missing (and what Sandro was referring to when referencing "cache") -- with the way it's currently structured, the first half will already be cached in Docker when `STEAM_VERSION` changes, and Docker will only re-execute the latter half (all the lines following `ENV STEAM_VERSION`).

When debugging the build it is also *very* useful to have multiple discrete layers so that if the `steam.deb` download step is failing, I can hop into a new container and run *just* that bit to test it interactively and figure out what's failing (especially given just how heavy those first set of dependencies are -- `docker history tianon/steam` shows that they're ~340MB, so this is a pretty dramatic speed increase during my development/testing).

Also, I've only got one host I actually `docker build` this on -- every other host I use simply downloads the image that host built/pushed to `tianon/steam` on Docker Hub, so build speed really isn't much of an issue for me.  This build also happens in the background via a Jenkins job that also builds many other images, so even if the build took half as long, I frankly wouldn't notice.
